# -*- coding: utf-8 -*-
"""Detecting Parkinson’s Disease.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wKZX2UaW0JTtgVwtWfQiI8gytfJGQBhq
"""

pip install numpy pandas sklearn xgboost

import numpy as np
import pandas as pd
import os, sys
from sklearn.preprocessing import MinMaxScaler
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# We Read the data
df=pd.read_csv('/content/drive/My Drive/Extract Files Zips/parkinsons.data')
df.head()

# We get the features and labels
features=df.loc[:,df.columns!='status'].values[:,1:]
labels=df.loc[:,'status'].values

# We get the count of each label (0 and 1) in labels
print(labels[labels==1].shape[0], labels[labels==0].shape[0])

# We scale the features to between -1 and 1
scaler=MinMaxScaler((-1,1))
x=scaler.fit_transform(features)
y=labels

# We split the dataset
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2, random_state=7)

#We train the model
model=XGBClassifier()
model.fit(x_train,y_train)

# We calculate the accuracy
y_pred=model.predict(x_test)
print(accuracy_score(y_test, y_pred)*100)